defaults:
  - dataset: pets_facial_expression  # choice [people_facial_expression, pets_facial_expression]
  - augmentations: default_augmentations
  - optimizer: adamw  # choice [adam, adamw, sgd]
  - scheduler: cosine_annealing_lr  # choice [step_lr_scheduler, cosine_annealing_lr]
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    optuna_config:
      direction: "maximize"
      study_name: null
      storage: null
      n_trials: 20
      n_jobs: 2
      seed: 42
      sampler: tpe

# if true, simulate a failure by raising an exception
error: false

params:
  device: cuda
  epochs: 50
  learning_rate: 1e-3
  batch_size: 64
  seed: 42

model:
  model_type: efficientnet_b0  # choice [mobilenet_v3_l, efficientnet_b0, shufflenet_v2_x2_0]
  criterion:
    _target_: torch.nn.CrossEntropyLoss
    label_smoothing: 0.0  

paths:
  log_file: ./runs
  data: ${hydra:runtime.cwd}/../data/raw
  model_checkpoint: best_model.pth