dataset:
  name: pets_facial_expression
  num_classes: 4
  train_data: ${hydra:runtime.cwd}\data\pets_facial_expression/Master Folder/train
  dev_data: ${hydra:runtime.cwd}\data\pets_facial_expression/Master Folder/valid
  test_data: ${hydra:runtime.cwd}\data\pets_facial_expression/Master Folder/test
augmentations:
  train_augmentations:
    _target_: torchvision.transforms.Compose
    transforms:
    - _target_: torchvision.transforms.Resize
      size:
      - 256
      - 256
    - _target_: torchvision.transforms.GaussianBlur
      kernel_size: 7
    - _target_: torchvision.transforms.RandomHorizontalFlip
    - _target_: torchvision.transforms.RandomRotation
      degrees: 15
      fill: 0
    - _target_: torchvision.transforms.RandomCrop
      size:
      - 224
      - 224
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
  test_augmentations:
    _target_: torchvision.transforms.Compose
    transforms:
    - _target_: torchvision.transforms.Resize
      size:
      - 256
      - 256
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 0.01
  amsgrad: false
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 10
  gamma: 0.5
  verbose: false
error: false
params:
  device: cuda
  epochs: 4
  learning_rate: 0.001
  batch_size: 64
  seed: 42
model:
  model_type: efficientnet_b0
  freeze_backbone: true
  criterion:
    _target_: torch.nn.CrossEntropyLoss
    label_smoothing: 0.0
paths:
  log_file: ./runs
  data: ${hydra:runtime.cwd}/../data/raw
  model_checkpoint: best_model.pth
